#tomcat port
server:
  port: 9002
#jsp
spring:
  thymeleaf:
    cache: false
#mysql setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leebj
    username: leebj
    password: 1234
#mybatis
mybatis:
  type-aliases-package: product.*
  mapper-locations:
  - /mapper/**/*.xml
